### PR TITLE
Match config keys with config.json

### PR DESCRIPTION
**Pull request by pat-sullivan**

### CODE REVIEW

**Comment by pat-sullivan** [comment]
I forgot to update the readme as well to match.

**Comment by sychen52** [comment]
My google auth recently keeps giving me timeout. Does yours still work?

**Comment by pat-sullivan** [comment]
It worked when testing for a few minutes, I'll let it run for longer and see what happens.

**Comment by pat-sullivan** [comment]
After having it running for just over an hour, I've gotten 9 errors. Some timeouts, some 403s... but it's still going strong. Just skips over the screenshot for that timestamp. 

I'm thinking the auth code from nest-observe needs to be wrapped in a try/catch, or maybe some kind of conditional that looks to see if one of the pings doesn't grab any data.

I might mess around with it if I have some free time. Trying my best to stop paying Nest every month!

**Comment by sychen52** [comment]
I got those errors all the time, and it does not bother the usage. However, about a week ago, I can no longer log in google auth. It keeps giving me a timeout. I guess google did something to their auth, which I have not figured out yet.

**Comment by pat-sullivan** [comment]
Oh that’s strange. It worked for me. Did you try grabbing new creds from the nest-homebridge instructions?

**Comment by sychen52** [comment]
Never mind. It works again this morning. I updated the creds a few days ago, and it did not work. This morning, it just worked again. Not sure why. Anyway, never mind.

**Pull request merged**
